In [1]:
import pandas as pd
import datetime
import numpy as np
import sklearn
from sklearn.cross_validation import train_test_split 
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.grid_search import GridSearchCV
from sklearn import linear_model
from sklearn.metrics import *
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


In [2]:
d1=pd.read_csv("C:/Users/nitin/Downloads/Dataset/Dataset/Training/Features_Variant_1.csv")
d2=pd.read_csv("C:/Users/nitin/Downloads/Dataset/Dataset/Training/Features_Variant_2.csv")
d3=pd.read_csv("C:/Users/nitin/Downloads/Dataset/Dataset/Training/Features_Variant_3.csv")
d4=pd.read_csv("C:/Users/nitin/Downloads/Dataset/Dataset/Training/Features_Variant_4.csv")
d5=pd.read_csv("C:/Users/nitin/Downloads/Dataset/Dataset/Training/Features_Variant_5.csv")

In [3]:
frames_main = [d1 , d2 , d3 , d4 , d5]

In [4]:
df = pd.concat(frames_main)

In [6]:
print (df.shape)

(327244, 54)


RFECV

In [54]:
RFECV

sklearn.feature_selection.rfe.RFECV

In [28]:
from sklearn.datasets import make_friedman1
from sklearn.feature_selection import RFECV
from sklearn.svm import SVR

In [48]:
df_train_lr,df_test_lr = train_test_split(df,train_size=0.7,random_state=42)
x_train_lr=df_train_lr.iloc[:,1:53]
y_train_lr=df_train_lr['Target_variable']
scaler.fit(x_train_lr)
x_train_sc_lr=scaler.transform(x_train_lr)
x_test_lr=df_test_lr.iloc[:,1:53]
y_test_lr=df_test_lr['Target_variable']
scaler.fit(x_test_lr)
x_test_sc_lr=scaler.transform(x_test_lr)

In [49]:
estimator = linear_model.LinearRegression()

In [50]:
selector = RFECV(estimator, step=1, cv=5)
selector.fit(x_train_sc_lr,y_train_lr )

RFECV(cv=5,
   estimator=LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False),
   n_jobs=1, scoring=None, step=1, verbose=0)

In [51]:
selector.support_ 

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [52]:
selector.ranking_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [53]:
x_train_lr.columns[selector.support_]

Index(['Page_visited_no_of_times', 'Page_talking_about', 'Page_category', 'c1',
       'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10', 'c11', 'c12',
       'c13', 'c14', 'c15', 'c16', 'c17', 'c18', 'c19', 'c20', 'c21', 'c22',
       'c23', 'c24', 'c25', 'CC1', 'CC2', 'CC3', 'CC4', 'CC5',
       'Base_time_something', 'Post_length_char_count', 'Post_share_count',
       'Post_promoted', 'Time_target', 'Sunday_post', 'Monday_post',
       'Tuesday_post', 'Wednesday_post', 'Thrusday_post', 'Friday_post',
       'Saturday_post', 'Sunday_base', 'Monday_base', 'Tuesday_base',
       'Wednesday_base', 'Thrusday_base', 'Friday_base', 'Saturday_base'],
      dtype='object')

In [55]:
df_train_dt,df_test_dt = train_test_split(df,train_size=0.7,random_state=42)
x_train_dt=df_train_dt.iloc[:,1:53]
y_train_dt=df_train_dt['Target_variable']
scaler.fit(x_train_dt)
x_train_sc_dt=scaler.transform(x_train_dt)
x_test_dt=df_test_dt.iloc[:,1:53]
y_test_dt=df_test_dt['Target_variable']
scaler.fit(x_test_dt)
x_test_sc_dt=scaler.transform(x_test_dt)

In [56]:
from sklearn import tree
dt_estimator = tree.DecisionTreeRegressor()

In [57]:
selector = RFECV(dt_estimator, step=1, cv=5)
selector.fit(x_train_sc_dt,y_train_dt )

RFECV(cv=5,
   estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
   n_jobs=1, scoring=None, step=1, verbose=0)

In [58]:
selector.support_ 

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False], dtype=bool)

In [59]:
selector.ranking_

array([36,  8, 19, 48, 11, 22, 29, 21, 51, 25,  7, 42, 18, 50, 24, 14, 45,
       20, 49, 32,  1, 17,  5, 12, 15, 10, 46, 23,  9,  4, 35, 13, 16,  3,
        2,  6, 52, 47, 34, 28, 30, 27, 33, 26, 31, 39, 43, 44, 38, 40, 37,
       41])